"""Tests for aphex.converter — model conversion to deployment formats."""
from __future__ import annotations

from pathlib import Path

import pytest
import torch
import torch.nn as nn

from aphex.converter import (
    _ONNX_BACKENDS,
    _OV_BACKENDS,
    _PYTORCH_BACKENDS,
    _TRT_BACKENDS,
    ALL_CONVERTIBLE,
    _parse_scalar,
    convert,
    default_output_path,
    read_deployment_yaml,
)

# ── Fixtures ──────────────────────────────────────────────────────────────────


def _tiny_model() -> nn.Module:
    """Linear 4→3, identity-ish weights for deterministic outputs."""
    m = nn.Linear(4, 3, bias=False)
    nn.init.eye_(m.weight[:3, :3])
    m.weight.data[2, 3] = 0.0
    return m.eval()


_INPUT_SHAPE = [4]


# ── Backend set sanity ────────────────────────────────────────────────────────


def test_all_convertible_non_empty() -> None:
    assert len(ALL_CONVERTIBLE) >= 12


def test_pytorch_backends_in_all_convertible() -> None:
    assert _PYTORCH_BACKENDS <= ALL_CONVERTIBLE


def test_onnx_backends_in_all_convertible() -> None:
    assert _ONNX_BACKENDS <= ALL_CONVERTIBLE


def test_trt_backends_in_all_convertible() -> None:
    assert _TRT_BACKENDS <= ALL_CONVERTIBLE


def test_ov_backends_in_all_convertible() -> None:
    assert _OV_BACKENDS <= ALL_CONVERTIBLE


def test_torch_compile_not_convertible() -> None:
    assert "torch_compile_fp32" not in ALL_CONVERTIBLE


# ── default_output_path ───────────────────────────────────────────────────────


def test_default_output_path_onnx() -> None:
    p = default_output_path(Path("/models/resnet50.pt"), "onnx_cpu")
    assert p == Path("/models/resnet50_onnx_cpu.onnx")


def test_default_output_path_tensorrt() -> None:
    p = default_output_path(Path("/models/resnet50.pt"), "tensorrt_fp16")
    assert p == Path("/models/resnet50_tensorrt_fp16.engine")


def test_default_output_path_pytorch_int8() -> None:
    p = default_output_path(Path("/models/resnet50.pt"), "pytorch_int8_dynamic")
    assert p == Path("/models/resnet50_pytorch_int8_dynamic.pt")


def test_default_output_path_openvino() -> None:
    p = default_output_path(Path("/models/resnet50.pt"), "openvino_fp32")
    assert p == Path("/models/resnet50_openvino_fp32.xml")


def test_default_output_path_unknown_backend() -> None:
    p = default_output_path(Path("/models/m.pt"), "custom_backend")
    assert p.suffix == ".bin"


def test_default_output_path_preserves_parent() -> None:
    p = default_output_path(Path("/some/deep/path/model.pt"), "onnx_int8_cpu")
    assert p.parent == Path("/some/deep/path")


# ── _parse_scalar ─────────────────────────────────────────────────────────────


def test_parse_scalar_null() -> None:
    assert _parse_scalar("null") is None


def test_parse_scalar_true() -> None:
    assert _parse_scalar("true") is True


def test_parse_scalar_false() -> None:
    assert _parse_scalar("false") is False


def test_parse_scalar_int() -> None:
    assert _parse_scalar("42") == 42


def test_parse_scalar_float() -> None:
    assert abs(_parse_scalar("3.14") - 3.14) < 1e-9  # type: ignore[operator]


def test_parse_scalar_quoted_string() -> None:
    assert _parse_scalar('"hello world"') == "hello world"


def test_parse_scalar_quoted_with_escape() -> None:
    assert _parse_scalar(r'"say \"hi\""') == 'say "hi"'


def test_parse_scalar_bare_string() -> None:
    result = _parse_scalar("something")
    assert result == "something"


# ── read_deployment_yaml ──────────────────────────────────────────────────────

_SAMPLE_YAML = """\
# Generated by aphex optimize
# 2026-06-16T00:00:00+00:00

model:
  path: "/models/resnet50.pt"
  framework: "pytorch"
  family: "cnn"
  parameters: 25000000
  input_shape: "3,224,224"
recommendation:
  backend: "tensorrt_fp16"
  dtype: "fp16"
  device: "cuda"
  batch_size: 4
  description: "TensorRT FP16 (CUDA)"
performance:
  latency_p50_ms: 3.5
  latency_p95_ms: 4.0
  latency_p99_ms: 4.5
  throughput_rps: 285.0
  memory_mb: 420.0
  accuracy_drop: null
  eval_metric: null
  eval_score: null
constraints:
  objective: "latency"
  max_latency_ms: null
  max_memory_mb: null
  min_throughput_rps: null
  max_quality_loss: null
meta:
  generated_at: "2026-06-16T00:00:00+00:00"
  tool: "aphex"
"""


def test_read_yaml_model_section(tmp_path: Path) -> None:
    f = tmp_path / "deployment.yaml"
    f.write_text(_SAMPLE_YAML)
    d = read_deployment_yaml(f)
    assert d["model"]["framework"] == "pytorch"
    assert d["model"]["parameters"] == 25_000_000
    assert d["model"]["input_shape"] == "3,224,224"


def test_read_yaml_recommendation_backend(tmp_path: Path) -> None:
    f = tmp_path / "deployment.yaml"
    f.write_text(_SAMPLE_YAML)
    d = read_deployment_yaml(f)
    assert d["recommendation"]["backend"] == "tensorrt_fp16"
    assert d["recommendation"]["batch_size"] == 4


def test_read_yaml_null_values(tmp_path: Path) -> None:
    f = tmp_path / "deployment.yaml"
    f.write_text(_SAMPLE_YAML)
    d = read_deployment_yaml(f)
    assert d["performance"]["accuracy_drop"] is None
    assert d["constraints"]["max_latency_ms"] is None


def test_read_yaml_float_values(tmp_path: Path) -> None:
    f = tmp_path / "deployment.yaml"
    f.write_text(_SAMPLE_YAML)
    d = read_deployment_yaml(f)
    assert abs(d["performance"]["latency_p50_ms"] - 3.5) < 1e-9


# ── convert: unknown backend ──────────────────────────────────────────────────


def test_convert_unknown_backend_raises(tmp_path: Path) -> None:
    model = _tiny_model()
    with pytest.raises(ValueError, match="Unsupported backend"):
        convert(model, "nonexistent_backend", _INPUT_SHAPE, tmp_path / "out.bin")


# ── convert: pytorch backends ─────────────────────────────────────────────────


def test_convert_pytorch_fp32_saves_pt(tmp_path: Path) -> None:
    out = tmp_path / "model_fp32.pt"
    written = convert(_tiny_model(), "pytorch_fp32", _INPUT_SHAPE, out)
    assert written == [out]
    assert out.exists()


def test_convert_pytorch_fp32_loadable(tmp_path: Path) -> None:
    out = tmp_path / "model_fp32.pt"
    convert(_tiny_model(), "pytorch_fp32", _INPUT_SHAPE, out)
    loaded = torch.load(out, weights_only=False)
    assert isinstance(loaded, nn.Module)


def test_convert_pytorch_fp16_weights_are_half(tmp_path: Path) -> None:
    out = tmp_path / "model_fp16.pt"
    convert(_tiny_model(), "pytorch_fp16", _INPUT_SHAPE, out)
    loaded = torch.load(out, weights_only=False)
    params = list(loaded.parameters())
    assert all(p.dtype == torch.float16 for p in params)


def test_convert_pytorch_bf16_weights_are_bfloat16(tmp_path: Path) -> None:
    out = tmp_path / "model_bf16.pt"
    convert(_tiny_model(), "pytorch_bf16", _INPUT_SHAPE, out)
    loaded = torch.load(out, weights_only=False)
    params = list(loaded.parameters())
    assert all(p.dtype == torch.bfloat16 for p in params)


def test_convert_scripted_module_pytorch_fp32(tmp_path: Path) -> None:
    # Regression: torch.save can't pickle a ScriptModule; converter must fall
    # back to torch.jit.save so scripted models (e.g. resnet18.pt) round-trip.
    scripted = torch.jit.script(_tiny_model())
    out = tmp_path / "scripted_fp32.pt"
    written = convert(scripted, "pytorch_fp32", _INPUT_SHAPE, out)
    assert written == [out]
    reloaded = torch.jit.load(str(out))
    x = torch.randn(1, 4)
    assert torch.allclose(scripted(x), reloaded(x), atol=1e-6)


def test_convert_scripted_module_pytorch_fp16(tmp_path: Path) -> None:
    scripted = torch.jit.script(_tiny_model())
    out = tmp_path / "scripted_fp16.pt"
    convert(scripted, "pytorch_fp16", _INPUT_SHAPE, out)
    reloaded = torch.jit.load(str(out))
    assert all(p.dtype == torch.float16 for p in reloaded.parameters())


def test_convert_pytorch_int8_dynamic_creates_file(tmp_path: Path) -> None:
    out = tmp_path / "model_int8.pt"
    written = convert(_tiny_model(), "pytorch_int8_dynamic", _INPUT_SHAPE, out)
    assert out.exists()
    assert written == [out]


def test_convert_does_not_mutate_original_model(tmp_path: Path) -> None:
    model = _tiny_model()
    original_dtype = next(model.parameters()).dtype
    convert(model, "pytorch_fp16", _INPUT_SHAPE, tmp_path / "out.pt")
    assert next(model.parameters()).dtype == original_dtype


def test_convert_creates_parent_dirs(tmp_path: Path) -> None:
    out = tmp_path / "deep" / "nested" / "model.pt"
    convert(_tiny_model(), "pytorch_fp32", _INPUT_SHAPE, out)
    assert out.exists()


# ── convert: ONNX backends ────────────────────────────────────────────────────


def test_convert_onnx_cpu_creates_file(tmp_path: Path) -> None:
    pytest.importorskip("onnxruntime")
    out = tmp_path / "model.onnx"
    written = convert(_tiny_model(), "onnx_cpu", _INPUT_SHAPE, out)
    assert out.exists()
    assert written == [out]


def test_convert_onnx_cpu_file_is_valid_onnx(tmp_path: Path) -> None:
    pytest.importorskip("onnxruntime")
    onnx = pytest.importorskip("onnx")
    out = tmp_path / "model.onnx"
    convert(_tiny_model(), "onnx_cpu", _INPUT_SHAPE, out)
    model_proto = onnx.load(str(out))
    onnx.checker.check_model(model_proto)


def test_convert_onnx_cpu_is_runnable(tmp_path: Path) -> None:
    ort = pytest.importorskip("onnxruntime")
    import numpy as np

    out = tmp_path / "model.onnx"
    convert(_tiny_model(), "onnx_cpu", _INPUT_SHAPE, out)
    sess = ort.InferenceSession(str(out), providers=["CPUExecutionProvider"])
    x = np.random.randn(1, 4).astype(np.float32)
    outputs = sess.run(None, {"input": x})
    assert outputs[0].shape == (1, 3)


def test_convert_onnx_int8_creates_file(tmp_path: Path) -> None:
    pytest.importorskip("onnxruntime")
    out = tmp_path / "model_int8.onnx"
    written = convert(_tiny_model(), "onnx_int8_cpu", _INPUT_SHAPE, out)
    assert out.exists()
    assert written == [out]


def test_convert_onnx_int8_file_is_smaller_than_fp32(tmp_path: Path) -> None:
    pytest.importorskip("onnxruntime")
    model = nn.Sequential(
        nn.Linear(64, 128, bias=False),
        nn.ReLU(),
        nn.Linear(128, 64, bias=False),
    ).eval()
    fp32 = tmp_path / "model.onnx"
    int8 = tmp_path / "model_int8.onnx"
    convert(model, "onnx_cpu", [64], fp32)
    convert(model, "onnx_int8_cpu", [64], int8)
    assert int8.stat().st_size < fp32.stat().st_size


# ── convert: TensorRT (skipped if not available) ──────────────────────────────


def test_convert_tensorrt_fp32_creates_engine(tmp_path: Path) -> None:
    pytest.importorskip("tensorrt")
    out = tmp_path / "model.engine"
    written = convert(_tiny_model(), "tensorrt_fp32", _INPUT_SHAPE, out)
    assert out.exists()
    assert written == [out]


def test_convert_tensorrt_int8_without_calibration_raises(tmp_path: Path) -> None:
    pytest.importorskip("tensorrt")
    out = tmp_path / "model.engine"
    with pytest.raises(RuntimeError, match="calibration data"):
        convert(_tiny_model(), "tensorrt_int8", _INPUT_SHAPE, out)


# ── convert: OpenVINO (skipped if not available) ─────────────────────────────


def test_convert_openvino_int8_without_calibration_raises(tmp_path: Path) -> None:
    pytest.importorskip("openvino")
    out = tmp_path / "model.xml"
    with pytest.raises(RuntimeError, match="calibration data"):
        convert(_tiny_model(), "openvino_int8", _INPUT_SHAPE, out)


def test_convert_openvino_fp32_creates_xml_and_bin(tmp_path: Path) -> None:
    pytest.importorskip("openvino")
    out = tmp_path / "model.xml"
    written = convert(_tiny_model(), "openvino_fp32", _INPUT_SHAPE, out)
    xml = tmp_path / "model.xml"
    bin_ = tmp_path / "model.bin"
    assert xml.exists()
    assert bin_.exists()
    assert set(written) == {xml, bin_}


# ── convert: sklearn / tree-ensemble backends ─────────────────────────────────


def _logreg(n_features: int = 4):
    import numpy as np
    from sklearn.linear_model import LogisticRegression

    X = np.random.randn(20, n_features)
    y = [0, 1] * 10
    return LogisticRegression(max_iter=200).fit(X, y)


def _forest(n_features: int = 4):
    import numpy as np
    from sklearn.ensemble import RandomForestClassifier

    X = np.random.randn(20, n_features)
    y = [0, 1] * 10
    return RandomForestClassifier(n_estimators=2, max_depth=2).fit(X, y)


def test_convert_sklearn_onnx_cpu_creates_file(tmp_path: Path) -> None:
    pytest.importorskip("sklearn")
    pytest.importorskip("skl2onnx")
    out = tmp_path / "logreg.onnx"
    written = convert(_logreg(), "onnx_cpu", [4], out)
    assert out.exists()
    assert written == [out]


def test_convert_sklearn_onnx_cpu_is_valid_onnx(tmp_path: Path) -> None:
    pytest.importorskip("sklearn")
    pytest.importorskip("skl2onnx")
    onnx = pytest.importorskip("onnx")
    out = tmp_path / "logreg.onnx"
    convert(_logreg(), "onnx_cpu", [4], out)
    onnx.checker.check_model(onnx.load(str(out)))


def test_convert_sklearn_onnx_cpu_is_runnable(tmp_path: Path) -> None:
    pytest.importorskip("sklearn")
    pytest.importorskip("skl2onnx")
    ort = pytest.importorskip("onnxruntime")
    import numpy as np

    n_features = 4
    out = tmp_path / "logreg.onnx"
    convert(_logreg(n_features), "onnx_cpu", [n_features], out)
    sess = ort.InferenceSession(str(out), providers=["CPUExecutionProvider"])
    x = np.random.randn(3, n_features).astype(np.float32)
    input_name = sess.get_inputs()[0].name
    outputs = sess.run(None, {input_name: x})
    assert len(outputs) > 0


def test_convert_forest_onnx_cpu_creates_file(tmp_path: Path) -> None:
    pytest.importorskip("sklearn")
    pytest.importorskip("skl2onnx")
    out = tmp_path / "forest.onnx"
    written = convert(_forest(), "onnx_cpu", [4], out)
    assert out.exists()
    assert written == [out]


def test_convert_sklearn_onnx_int8_raises(tmp_path: Path) -> None:
    pytest.importorskip("sklearn")
    out = tmp_path / "model.onnx"
    with pytest.raises(RuntimeError, match="not supported for traditional ML"):
        convert(_logreg(), "onnx_int8_cpu", [4], out)


def test_convert_sklearn_does_not_mutate_model(tmp_path: Path) -> None:
    pytest.importorskip("sklearn")
    pytest.importorskip("skl2onnx")
    model = _logreg()
    coef_before = model.coef_.copy()
    convert(model, "onnx_cpu", [4], tmp_path / "out.onnx")
    import numpy as np
    assert np.array_equal(model.coef_, coef_before)


def test_convert_sklearn_default_output_path_extension(tmp_path: Path) -> None:
    p = default_output_path(tmp_path / "model.joblib", "onnx_cpu")
    assert p.suffix == ".onnx"


# ── multi-input conversion ──────────────────────────────────────────────────


class _TwoInputNet(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.a = nn.Linear(4, 8)
        self.b = nn.Linear(6, 8)
        self.head = nn.Linear(8, 3)

    def forward(self, x, y):  # noqa: ANN001
        return self.head(torch.relu(self.a(x) + self.b(y)))


def test_convert_multi_input_onnx_names_inputs(tmp_path: Path) -> None:
    pytest.importorskip("onnxruntime")
    import onnxruntime as ort

    from aphex.inputspec import InputSpec

    spec = InputSpec.parse("x:4;y:6")
    out = tmp_path / "multi.onnx"
    convert(_TwoInputNet().eval(), "onnx_cpu", spec.primary_shape, out, input_spec=spec)
    names = [i.name for i in ort.InferenceSession(str(out)).get_inputs()]
    assert names == ["x", "y"]


def test_convert_multi_input_tensorrt_raises(tmp_path: Path) -> None:
    from aphex.inputspec import InputSpec

    spec = InputSpec.parse("x:4;y:6")
    with pytest.raises(RuntimeError, match="multi-input"):
        convert(_TwoInputNet().eval(), "tensorrt_fp16", spec.primary_shape,
                tmp_path / "x.engine", input_spec=spec)


def test_convert_multi_input_openvino_raises(tmp_path: Path) -> None:
    from aphex.inputspec import InputSpec

    spec = InputSpec.parse("x:4;y:6")
    with pytest.raises(RuntimeError, match="multi-input"):
        convert(_TwoInputNet().eval(), "openvino_fp32", spec.primary_shape,
                tmp_path / "x.xml", input_spec=spec)
